### ISSUE TITLE
特徴量空間でのプロットに際してサンプリングをちゃんと行っていないのでは？

### ISSUE THREAD

**Issue by kazucmpt** [matsuken92/Qiita_Contents#1]
Qiitaから流れてきました。

num_latetn=2としたときの特徴量空間の描画についてお伺いします。具体的には、Qiita_Contents/chainer-vae/chainer-vae.ipynbのIn [32]です。

z_mu = model.encode(chainer.cuda.to_gpu(x_sample))[0]として、これをそのまま2次元プロットしていますが、正しくは、

mu, in_var = model.encode(chainer.cuda.to_gpu(x_sample))
としたあとに、
z = F.gaussian(mu, in_var)
とちゃんとガウシアンからサンプルしたものをプロットしないといけないのではないでしょうか。もちろん、varがそんなに大きくなければ、ガウシアンからプロットした結果はおおよそmuになるので、やっていることはわかるのですが、一言説明を加えるべきではないかなと思いました。

ご回答のほど、よろしくお願いします。

**Comment by matsuken92** [comment]
@kazucmpt さん、コメントありがとうございます。
学習時はサンプリングしてDecoderに流しますが、推論時はz_muを使うということはおかしくないのではと思っています。（最尤法と考えればいいと思います）いかがでしょうか？

**Comment by kazucmpt** [comment]
理解しました。ありがとうございます。
